version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bank-challenge-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poc_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-challenge
    container_name: bank-challenge-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - poc_network

volumes:
  postgres_data:

networks:
  poc_network:
    driver: bridge
